version: '3'
services:
  elasticDB-primary:
    image: elasticsearch:8.9.0
    container_name: elasticDB-primary
    volumes:
      - ./data/elastic-primary:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=post-read-db
      - node.name=node-1
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
      - discovery.seed_hosts=elasticDB-primary,elasticDB-secondary,elasticDB-tertiary
      - cluster.initial_master_nodes=node-1,node-2,node-3
      - network.host=0.0.0.0
    networks:
      - db-network

  elasticDB-secondary:
    image: elasticsearch:8.9.0
    container_name: elasticDB-secondary
    volumes:
      - ./data/elastic-secondary:/usr/share/elasticsearch/data
    depends_on:
      - elasticDB-primary
    environment:
      - cluster.name=post-read-db
      - node.name=node-2
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
      - discovery.seed_hosts=elasticDB-primary,elasticDB-secondary,elasticDB-tertiary
      - cluster.initial_master_nodes=node-1,node-2,node-3
      - network.host=0.0.0.0
    ports:
      - 9201:9200
    networks:
      - db-network

  elasticDB-tertiary:
    image: elasticsearch:8.9.0
    container_name: elasticDB-tertiary
    volumes:
      - ./data/elastic-tertiary:/usr/share/elasticsearch/data
    depends_on:
      - elasticDB-primary
    environment:
      - cluster.name=post-read-db
      - node.name=node-3
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
      - discovery.seed_hosts=elasticDB-primary,elasticDB-secondary,elasticDB-tertiary
      - cluster.initial_master_nodes=node-1,node-2,node-3
      - network.host=0.0.0.0
    ports:
      - 9203:9200
    networks:
      - db-network

networks:
  db-network: